### ISSUE TITLE
token logger

### ISSUE THREAD

**Issue by ya-ilya** [HeroGlaucoP/1pop-client#7]
lmao

**Comment by wawddd** [comment]
retard stfu

**Comment by ya-ilya** [comment]
> retard stfu

https://github.com/HeroGlaucoP/1pop-client/blob/ce2340ff0dc0ce4a59e7cf64c28b5f44991b9cf4/build/sources/main/java/me/zeroeightsix/kami/util/WurstplusCapeManager.java

**Comment by HeroGlaucoP** [comment]
it was an attempt to token log a friend of mine, but i didn't figure out how the logger worked, so i removed it
